FROM mcr.microsoft.com/playwright/python:v1.55.0-jammy

WORKDIR /home/app

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Bogota

# 🔹 INSTALAR tzdata del sistema
RUN apt-get update \
    && apt-get install -y tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /home/app

CMD ["python", "main.py"]
