FROM python:3.12-slim

# Instalar curl
RUN apt-get update && apt-get install -y curl

# Copiar la aplicación
WORKDIR /home/app


# 🔹 Evitar prompts interactivos en la instalación
ENV DEBIAN_FRONTEND=noninteractive

# 🔹 Configurar zona horaria por defecto (Bogotá)
ENV TZ=America/Bogota


COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

COPY . /home/app

# Exponer el puerto
EXPOSE 5080

# Comando para ejecutar la aplicación
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5080"]

#uvicorn main:app --host 0.0.0.0 --port 5080