FROM mcr.microsoft.com/playwright/python:v1.55.0-jammy


WORKDIR /home/app

# 🔹 Evitar prompts interactivos en la instalación
ENV DEBIAN_FRONTEND=noninteractive

# 🔹 Configurar zona horaria por defecto (Bogotá)
ENV TZ=America/Bogota

# 🔹 Copiar requirements y limpiar duplicados
COPY requirements.txt .


# 🔹 Instalar dependencias Python
RUN pip install --no-cache-dir -r requirements.txt

# 🔹 Copiar el código al contenedor
COPY . /home/app

# 🔹 Comando por defecto
CMD ["python", "main.py"]
